routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('/itemCRUD','ItemCRUDController');
Route::post('/itemCRUD/store', 'ItemCRUDController@store');
Route::get('/item/itemreg','ItemCRUDController@ItemRegister');
Route::post('/item/itemreg','ItemCRUDController@ItemCreate');
Route::get('/item/itemlist','ItemCRUDController@ItemList');
Route::get('/item/itemdelete/{id}','ItemCRUDController@ItemDelete');
Route::get('/item/itemedit/{id}','ItemCRUDController@ItemEdit');
Route::post('/item/itemupdate','ItemCRUDController@ItemUpdate');

Route::get('/Customer/CustomerList','CustomerController@CustomerList');

Route::get('/Customer/CustomerCreate','CustomerController@CustomerCreate');

Route::post('/Customer/CustomerCreate','CustomerController@CustomerSave');

Route::get('/Customer/CustomerDelete/{id}','CustomerController@CustomerDelete');

Route::get('/Customer/CustomerEdit/{id}','CustomerController@CustomerEdit');
Route::post('/Customer/CustomerEdit','CustomerController@CustomerUpdate');

Route::get('/ForFileUpload/FileUpload','ForFileUploadController@FileUpload');
Route::post('/ForFileUpload/FileUpload','ForFileUploadController@FileUploadSave');

Route::get('/ForFileUpload/download/{file}', 'ForFileUploadController@download');

Route::post('/Customer/CustomerSearch','CustomerController@CustomerSearch');

app/Models/Item.php
<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use DB;

class Item extends Model{
 
      protected $table = 'items';
     protected $primaryKey  = 'itemId'; 
     public $timestamps = false;

     
     public static function insertItem($data){


              $table=with(new static)->table;

               $result=DB::table($table)
                    ->insert($data);
                  return $result;
       
     }
     public static function getItemList(){
     	  $table=with(new static)->table;

     	    $result=DB::table($table)
     	           ->select('*')
     	           ->get();

     	           return $result;
     }
     public static function ItemDelete($itemId){

     	  $table=with(new static)->table;
     	   $rsult=DB::table($table)
     	          ->where('itemId','=',$itemId)
     	          ->delete();


     }
     public static function getEditData($itemId){


     	  $table=with(new static)->table;
     	   $result=DB::table($table)
     	          ->where('itemId','=',$itemId)
     	          ->select()
     	          ->get();

     	        return $result;


     }
      public static function ItemUpdate($dataUpdate){
        
        $itemId=$dataUpdate['itemId'];
        $data['title']=$dataUpdate['title'];
        $data['description']=$dataUpdate['description'];

     	  $table=with(new static)->table;
     	   $result=DB::table($table)
     	          ->where('itemId','=',$itemId)
     	          ->update($data); 

     }

    

  }
  ?>

resources/views/item/itemedit.blade.php
@extends('layouts.default')


@section('content')


    <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-left">

                <h2>Create New Item</h2>

            </div>

            <div class="pull-right">

                <a class="btn btn-primary" href="{{ route('itemCRUD.index') }}"> Back</a>

            </div>

        </div>

    </div>


    @if (count($errors) > 0)

        <div class="alert alert-danger">

            <strong>Whoops!</strong> There were some problems with your input.<br><br>

            <ul>

                @foreach ($errors->all() as $error)

                    <li>{{ $error }}</li>

                @endforeach

            </ul>

        </div>

    @endif



<form  method="POST" action="{{ url('/item/itemupdate') }}"  >
{!! csrf_field() !!}


    <div class="row">
      

      @foreach($editData as $edit)


        <input type="hidden" name="itemId"   value="{{ $edit->itemId  }}" id="title" placeholder="Title" style="height: 50px;" class="form-control">


        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Title:</strong>

             
                <input type="textarea" name="title"   value="{{ old('title',$edit->title)}}" id="title" placeholder="Title" style="height: 50px;" class="form-control">

            </div>

        </div>


        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Description:</strong>

               
                <input type="textarea" name="description"  value="{{ old('title',$edit->description)}}" id="description" placeholder="Description" style="height: 50px;" class="form-control">

            </div>

        </div>


        <div class="col-xs-12 col-sm-12 col-md-12 text-center">

                <button type="submit" class="btn btn-primary">Submit</button>

        </div>

        @endforeach


    </div>

</form>

@endsection

resources/views/item/itemlist.blade.php
            <div class="pull-right">

                <a class="btn btn-success" href="{{ url('item/itemreg')}}"> Create New Item</a>

            </div>

<table>
@foreach($ItemData as $item)
	<tr>
	<td>{{ $item->itemId }}</td>
	<td>{{ $item->title }}</td>
	<td>{{ $item->description }}</td>	
	<td><a href="{{  url('item/itemdelete/'.$item->itemId.'')}}">Delete</a></td>
	<td><a href="{{  url('item/itemedit/'.$item->itemId.'')}}">Edit</a></td>
	</tr>
@endforeach
</table>

resources/views/item/viewitem.blade.php
<?php
echo"hi";
?>