routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('/itemCRUD','ItemCRUDController');
Route::post('/itemCRUD/store', 'ItemCRUDController@store');
Route::get('/item/itemreg','ItemCRUDController@ItemRegister');
Route::post('/item/itemreg','ItemCRUDController@ItemCreate');
Route::get('/item/itemlist','ItemCRUDController@ItemList');
Route::get('/item/itemdelete/{id}','ItemCRUDController@ItemDelete');
Route::get('/item/itemedit/{id}','ItemCRUDController@ItemEdit');
Route::post('/item/itemupdate','ItemCRUDController@ItemUpdate');

Route::get('/Customer/CustomerList','CustomerController@CustomerList');

Route::get('/Customer/CustomerCreate','CustomerController@CustomerCreate');

Route::post('/Customer/CustomerCreate','CustomerController@CustomerSave');

Route::get('/Customer/CustomerDelete/{id}','CustomerController@CustomerDelete');

Route::get('/Customer/CustomerEdit/{id}','CustomerController@CustomerEdit');
Route::post('/Customer/CustomerEdit','CustomerController@CustomerUpdate');

Route::get('/ForFileUpload/FileUpload','ForFileUploadController@FileUpload');
Route::post('/ForFileUpload/FileUpload','ForFileUploadController@FileUploadSave');

Route::get('/ForFileUpload/download/{file}', 'ForFileUploadController@download');

Route::post('/Customer/CustomerSearch','CustomerController@CustomerSearch');

app/Http/Controllers/ItemCRUDController.php
<?php
namespace App\Http\Controllers;


use Illuminate\Http\Request;

use App\Http\Controllers\Controller;
use App\Models\Item;
use View;
use Validator;

class ItemCRUDController extends Controller

{


    /**

     * Display a listing of the resource.

     *

     * @return \Illuminate\Http\Response

     */

    public function index(Request $request)

    {

        $items = Item::orderBy('id','DESC')->paginate(5);

        return view('ItemCRUD.index',compact('items'))

            ->with('i', ($request->input('page', 1) - 1) * 5);

    }


    /**

     * Show the form for creating a new resource.

     *

     * @return \Illuminate\Http\Response

     */

    public function create()

    {

        return view('ItemCRUD.create');

    }


    /**

     * Store a newly created resource in storage.

     *

     * @param  \Illuminate\Http\Request  $request

     * @return \Illuminate\Http\Response

     */

    public function store(Request $request)

    {   
        

        $this->validate($request, [

            'title' => 'required',

            'description' => 'required',

        ]);


        Item::create($request->all());

   

    }


    /**

     * Display the specified resource.

     *

     * @param  int  $id

     * @return \Illuminate\Http\Response

     */

    public function show($id)

    {

        $item = Item::find($id);

        return view('ItemCRUD.show',compact('item'));

    }


    /**

     * Show the form for editing the specified resource.

     *

     * @param  int  $id

     * @return \Illuminate\Http\Response

     */

    public function edit($id)

    {

        $item = Item::find($id);

        return view('ItemCRUD.edit',compact('item'));

    }


    /**

     * Update the specified resource in storage.

     *

     * @param  \Illuminate\Http\Request  $request

     * @param  int  $id

     * @return \Illuminate\Http\Response

     */

    public function update(Request $request, $id)

    {

        $this->validate($request, [

            'title' => 'required',

            'description' => 'required',

        ]);


        Item::find($id)->update($request->all());

        return redirect()->route('itemCRUD.index')

                        ->with('success','Item updated successfully');

    }


    /**

     * Remove the specified resource from storage.

     *

     * @param  int  $id

     * @return \Illuminate\Http\Response

     */

    public function destroy($id)

    {

        Item::find($id)->delete();

        return redirect()->route('itemCRUD.index')

                        ->with('success','Item deleted successfully');

    }
    // public function viewItem(){
    //      return view('item.viewitem');
    // }
    // public function viewItem(){
    //     return redirect('create/item');

    // }
    public function ItemRegister(){
        return view('itemCRUD.create');

    }
    public function ItemCreate(request $request){

              $input=\Request::all();
              

   $validator=Validator::make($input,array("title"=>"required|email","description"=>"required"));

        if($validator->fails() )
        {
            return redirect('item/itemreg/')->withInput()->withErrors($validator);
         }
         else{
               $data=array();
              foreach ($input as $key => $value) {
                   if($key!='_token'){
                     $data[$key]=$value;
                   }
              }

              Item::insertItem($data);

              return redirect('item/itemlist');

         }
              

    }
    public function ItemList(){
       $data['ItemData']= Item::getItemList();

       return view('item.itemlist',$data);
    }
    public function ItemDelete($itemId){
          
          Item::ItemDelete($itemId);

          return redirect('item/itemlist');
    }
    public function itemEdit($itemId){

      $data['editData'] = Item::getEditData($itemId);

      return view('item.itemedit',$data);


    }
    public function itemUpdate(request $request){

          $input= \Request::all();

          $dataUpdate=array();
              
              foreach ($input as $key => $value) {
                   if($key!='_token'){
                     $dataUpdate[$key]=$value;
                   }
              }
              

             Item::ItemUpdate($dataUpdate);

             return redirect('item/itemlist');


    }

}

resources/views/ItemCRUD/create.blade.php
@extends('layouts.default')


@section('content')


    <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-left">

                <h2>Create New Item</h2>

            </div>

            <div class="pull-right">

                <a class="btn btn-primary" href="{{ route('itemCRUD.index') }}"> Back</a>

            </div>

        </div>

    </div>


    @if (count($errors) > 0)

        <div class="alert alert-danger">

            <strong>Whoops!</strong> There were some problems with your input.<br><br>

            <ul>

                @foreach ($errors->all() as $error)

                    <li>{{ $error }}</li>

                @endforeach

            </ul>

        </div>

    @endif



<form  method="POST" action="{{ url('/item/itemreg') }}"  >
{!! csrf_field() !!}


    <div class="row">


        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Title:</strong>

             
                <input type="textarea" name="title" value="{{ old('title')}}" id="title" placeholder="Title" style="height: 50px;" class="form-control">
                
                @if($errors->has('title'))
                   <span class="help-block">
                    <strong style="color:red">{{ $errors->first('title') }}</strong>
                    </span>
                 @endif

            </div>

        </div>


        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Description:</strong>

               
                <input type="textarea" name="description" value="{{ old('description') }}" id="description" placeholder="Description" style="height: 50px;" class="form-control">

                 @if($errors->has('description'))
                   <span class="help-block">
                    <strong style="color:red">{{ $errors->first('description') }}</strong>
                    </span>
                 @endif

            </div>

        </div>


        <div class="col-xs-12 col-sm-12 col-md-12 text-center">

                <button type="submit" class="btn btn-primary">Submit</button>

        </div>


    </div>

</form>

@endsection

resources/views/ItemCRUD/edit.blade.php
@extends('layouts.default')

 

@section('content')


    <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-left">

                <h2>Edit New Item</h2>

            </div>

            <div class="pull-right">

                <a class="btn btn-primary" href="{{ route('itemCRUD.index') }}"> Back</a>

            </div>

        </div>

    </div>


    @if (count($errors) > 0)

        <div class="alert alert-danger">

            <strong>Whoops!</strong> There were some problems with your input.<br><br>

            <ul>

                @foreach ($errors->all() as $error)

                    <li>{{ $error }}</li>

                @endforeach

            </ul>

        </div>

    @endif


    {!! Form::model($item, ['method' => 'PATCH','route' => ['itemCRUD.update', $item->id]]) !!}

    <div class="row">


        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Title:</strong>

                {!! Form::text('title', null, array('placeholder' => 'Title','class' => 'form-control')) !!}

            </div>

        </div>


        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>Description:</strong>

                {!! Form::textarea('description', null, array('placeholder' => 'Description','class' => 'form-control','style'=>'height:100px')) !!}

            </div>

        </div>


        <div class="col-xs-12 col-sm-12 col-md-12 text-center">

                <button type="submit" class="btn btn-primary">Submit</button>

        </div>


    </div>

    {!! Form::close() !!}


@endsection

resources/views/ItemCRUD/index.blade.php
@extends('layouts.default')

 

@section('content')


    <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-left">

                <h2>Items CRUD</h2>

            </div>

            <div class="pull-right">

                <a class="btn btn-success" href="{{ url('item/itemreg')}}"> Create New Item</a>

            </div>

        </div>

    </div>


   <!--  @if ($message = Session::get('success'))

        <div class="alert alert-success">

            <p>{{ $message }}</p>

        </div>

    @endif
 -->

   <!--  <table class="table table-bordered">

        <tr>

            <th>No</th>

            <th>Title</th>

            <th>Description</th>

            <th width="280px">Action</th>

        </tr>

    @foreach ($items as $key => $item)

    <tr>

        <td>{{ ++$i }}</td>

        <td>{{ $item->title }}</td>

        <td>{{ $item->description }}</td>

        <td>

            <a class="btn btn-info" href="{{ route('itemCRUD.show',$item->id) }}">Show</a>

            <a class="btn btn-primary" href="{{ route('itemCRUD.edit',$item->id) }}">Edit</a>

            {!! Form::open(['method' => 'DELETE','route' => ['itemCRUD.destroy', $item->id],'style'=>'display:inline']) !!}

            {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}

            {!! Form::close() !!}

        </td>

    </tr>

    @endforeach

    </table>
 -->

    {!! $items->render() !!}


@endsection

resources/views/ItemCRUD/show.blade.php
@extends('layouts.default')

 

@section('content')


    <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-left">

                <h2> Show Item</h2>

            </div>

           <!--  <div class="pull-right">

                <a class="btn btn-primary" href="{{ route('itemCRUD/index') }}"> Back</a>

            </div> -->

        </div>

    </div>


   


@endsection